version: "3.7"
services:
  frontend:
    build: ./frontend/
    ports:
      - 8003:3000
    volumes:
      - ./frontend/src:/application/src
  backend:
    build: ./backend/
    ports:
      - 8005:5000
    volumes:
      - ./backend/application.py:/application/application.py
    environment:
      - NEW_RELIC_APP_NAME=metrics-POC-backend
      - NEW_RELIC_NO_CONFIG_FILE=true
      - NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true
      - NEW_RELIC_LOG=stdout
      - NEW_RELIC_LICENSE_KEY=
  ads:
    build: ./ads/
    ports:
      - 8006:5000
    volumes:
      - ./ads/src:/application/src
    environment:
      - NEW_RELIC_APP_NAME=metrics-POC-ads
      - NEW_RELIC_NO_CONFIG_FILE=true
      - NEW_RELIC_LICENSE_KEY=
      - NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true
      - NEW_RELIC_LOG=stdout
